name: Deploy To AWS Lambda

on:
  push:
    branches:
      - master
    paths:
      - "escrows-adapter/*"

jobs:
  deploy:
    name: deploy
    env:
      working-directory: ./escrows-adapter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # skip test for now
      # - run: npm ci
      - name: Install Serverless Framework
        run: npm install -g serverless
        working-directory: ${{env.working-directory}}

      - name: Configure AWS credentials
        run: serverless config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
        working-directory: ${{env.working-directory}}

      - name: Install NPM dependencies
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: Deploy
        run: sls deploy
        working-directory: ${{env.working-directory}}
